#!/usr/bin/env python

import csv

with open('rel_input_sorted.csv', 'r', newline='') as input_file,\
        open('rel_output_address_sorted.csv', 'r', newline='') as output_address_file,\
        open('input_addresses.csv', 'w', newline='') as input_addresses_file:
    input_reader = csv.reader(input_file)
    output_address_reader = csv.reader(output_address_file)
    input_address_writer = csv.writer(input_addresses_file)
    last_output = ''
    last_address = ''
    for input_row in input_reader:
        txid = input_row[0]
        output_ref = input_row[1]

        match_address = last_address if output_ref == last_output else None

        for output_row in output_address_reader:
            output = output_row[0]
            address = output_row[1]
            if output_ref == output:
                if match_address is None:
                    match_address = address
                else:
                    match_address = None
                    last_output = output
                    last_address = address
                    break
            elif output_ref < output:
                last_output = output
                last_address = address
                break
            last_output = output
            last_address = address

        if match_address is not None:
            input_address_writer.writerow([txid, match_address])
