#!/usr/bin/env python

import csv

with open('rel_input_sorted.csv', 'r') as input_file,\
        open('rel_output_address_sorted.csv', 'r') as output_address_file,\
        open('input_addresses.csv', 'w') as input_addresses_file:
    input_address_writer = csv.writer(input_addresses_file)
    for line in input_file:
        entries = line.strip().split(',')
        txid = entries[0]
        output = entries[1]

        for line2 in output_address_file:
            entries2 = line2.strip().split(',')
            output2 = entries2[0]
            address = entries2[1]
            if output == output2:
                input_address_writer.writerow([txid, address])
                break
